import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "DevCaioDias",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className="bg-imgee bg-cover bg-center min-h-screen"
      >
        {children}
      </body>
    </html>
  );
}
